### ISSUE TITLE
Annotation check is not working as expected 

### ISSUE THREAD

**Issue by aabughosh** [litmuschaos/litmus-go#531]
## Is this a BUG REPORT or FEATURE REQUEST?
 
 Choose one: BUG REPORT or FEATURE REQUEST

BUG REPORT

**What happened**:

i tried to run the pod delete test with annotationcheck:true in the chaos engine and i see that the pod delete is stuck
i have two kind of pods that have the same label 2 of them are from kind deployment  and other two that are from statefulset 
and i want to test just the pods that are from kind deployment, so im using the annotation solution to test the test just on the deployment and i put in the chaos-engine file   annotationCheck: "true" and kubectl annotate deploy/test -n tnf litmuschaos.io/chaos="true"  .
the test is stuck (im seeing that the code stuck on this line when im seeing the pod delete pod   [Status]: Verify that the AUT (Application Under Test) is running (pre-chaos) )and on the describe of the chaos engine im seeing that it failed

**What you expected to happen**:
i expected from it to do pod delete just for the deployment pods
**How to reproduce it (as minimally and precisely as possible)**:
need to add more logs maybe inside the AnnotatedApplicationsStatusCheck function inside the try 

**Anything else we need to know?**:
why its stuck? how annotation work? why its not working in good way to me?

**Comment by janosdebugs** [comment]
I attempted to reproduce this issue using the following steps, to no avail:

1. Spin up a KinD cluster.
2. kubectl apply -f https://litmuschaos.github.io/litmus/litmus-operator-v2.9.0.yaml
3. kubectl apply -f https://hub.litmuschaos.io/api/chaos/2.9.0?file=charts/generic/experiments.yaml
4. Apply the following manifest:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx1
  namespace: default
  labels:
    app: nginx
    test: foo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx1
  template:
    metadata:
      labels:
        app: nginx1
        test: foo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx2
  namespace: default
  labels:
    app: nginx
    test: foo
  annotations:
    litmuschaos.io/chaos: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx2
  template:
    metadata:
      annotations:
        litmuschaos.io/chaos: "true"
      labels:
        app: nginx2
        test: foo
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litmus
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: litmus
  namespace: default
rules:
- apiGroups: ["","litmuschaos.io","batch","apps"]
  resources: ["pods","deployments","pods/log","events","jobs","chaosengines","chaosexperiments","chaosresults","replicasets"]
  verbs: ["create","list","get","patch","update","delete","deletecollection"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: litmus
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: litmus
subjects:
- kind: ServiceAccount
  name: litmus
  namespace: default
---
apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: engine-nginx
  namespace: default
spec:
  engineState: "active"
  annotationCheck: "true"
  chaosServiceAccount: litmus
  appinfo:
    appns: "default"
    applabel: "test=foo"
    appkind: "deployment"
  experiments:
  - name: pod-delete
```

In my experiment it was always `nginx2` being killed.
